name: SPCompile

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup SourcePawn Compiler
      uses: rumblefrog/setup-sp@master
      with:
        version: '1.11.x'
    - name: Compile tf2attributes
      run: spcomp scripting/tf2attributes.sp
    - name: Compile example
      run: spcomp -iscripting/include scripting/tf2attributes_example.sp
